[2024-09-11 16:16:24,307][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-11 16:16:37,417][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 1012536116.0, 'object_store_memory': 506268057.0, 'node:127.0.0.1': 1.0, 'node:__internal_head__': 1.0, 'CPU': 8.0}
[2024-09-11 16:16:37,419][flwr][INFO] - Initializing global parameters
[2024-09-11 16:16:37,420][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-11 16:16:43,819][flwr][ERROR] - [36mray::launch_and_get_parameters()[39m (pid=14364, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 135, in launch_and_get_parameters
    client: Client = _create_client(client_fn, cid)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 168, in _create_client
    client_like: ClientLike = client_fn(cid)
                              ^^^^^^^^^^^^^^
  File "c:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 58, in client_fn
    return FlowerClient(
           ^^^^^^^^^^^^^
TypeError: FlowerClient.__init__() got an unexpected keyword argument 'vallodaer'
