[2024-09-12 11:02:01,785][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-12 11:02:16,820][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 1628427879.0, 'node:__internal_head__': 1.0, 'object_store_memory': 814213939.0, 'CPU': 8.0, 'node:127.0.0.1': 1.0}
[2024-09-12 11:02:16,821][flwr][INFO] - Initializing global parameters
[2024-09-12 11:02:16,822][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 11:02:23,076][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 11:02:23,077][flwr][INFO] - Evaluating initial parameters
[2024-09-12 11:02:23,138][flwr][INFO] - initial parameters (loss, other metrics): 18.64792404174805, {'accuracy': 0.5616666666666666}
[2024-09-12 11:02:23,141][flwr][INFO] - FL starting
[2024-09-12 11:02:23,142][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 11:02:38,058][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=2656, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 45, in fit
    train(self.model, self.trainloader, optimizer, epochs, self.device)
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\model.py", line 28, in train
    optimizer.zero_grad()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'functools.partial' object has no attribute 'zero_grad'
[2024-09-12 11:02:44,233][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11084, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 45, in fit
    train(self.model, self.trainloader, optimizer, epochs, self.device)
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\model.py", line 28, in train
    optimizer.zero_grad()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'functools.partial' object has no attribute 'zero_grad'
[2024-09-12 11:02:44,239][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-12 11:02:44,298][flwr][INFO] - fit progress: (1, 18.64792404174805, {'accuracy': 0.5616666666666666}, 21.155853300000672)
[2024-09-12 11:02:44,300][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
