[2024-09-12 12:17:04,730][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-12 12:17:16,512][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'memory': 1767029147.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 883514572.0, 'CPU': 8.0}
[2024-09-12 12:17:16,514][flwr][INFO] - Initializing global parameters
[2024-09-12 12:17:16,515][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 12:17:27,257][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 12:17:27,258][flwr][INFO] - Evaluating initial parameters
[2024-09-12 12:17:27,307][flwr][INFO] - initial parameters (loss, other metrics): 31.622700246175132, {'accuracy': 0.5611111111111111}
[2024-09-12 12:17:27,308][flwr][INFO] - FL starting
[2024-09-12 12:17:27,309][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 12:17:27,351][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16728, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 38, in fit
    epochs = config["local_epochs"]
             ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'local_epochs'
[2024-09-12 12:17:34,285][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11336, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 38, in fit
    epochs = config["local_epochs"]
             ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'local_epochs'
[2024-09-12 12:17:34,291][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-12 12:17:34,362][flwr][INFO] - fit progress: (1, 31.622700246175132, {'accuracy': 0.5611111111111111}, 7.053036699999211)
[2024-09-12 12:17:34,363][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 12:17:46,582][flwr][DEBUG] - evaluate_round 1 received 2 results and 0 failures
[2024-09-12 12:17:46,583][flwr][DEBUG] - fit_round 2: strategy sampled 2 clients (out of 2)
[2024-09-12 12:17:46,608][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16728, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 38, in fit
    epochs = config["local_epochs"]
             ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'local_epochs'
[2024-09-12 12:17:46,609][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11336, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 38, in fit
    epochs = config["local_epochs"]
             ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'local_epochs'
[2024-09-12 12:17:46,617][flwr][DEBUG] - fit_round 2 received 0 results and 2 failures
[2024-09-12 12:17:46,661][flwr][INFO] - fit progress: (2, 31.622700246175132, {'accuracy': 0.5611111111111111}, 19.35269630000039)
[2024-09-12 12:17:46,663][flwr][DEBUG] - evaluate_round 2: strategy sampled 2 clients (out of 2)
