[2024-09-12 11:04:55,890][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-12 11:05:11,746][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 8.0, 'node:__internal_head__': 1.0, 'node:127.0.0.1': 1.0, 'memory': 1655193600.0, 'object_store_memory': 827596800.0}
[2024-09-12 11:05:11,748][flwr][INFO] - Initializing global parameters
[2024-09-12 11:05:11,748][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 11:05:17,851][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 11:05:17,852][flwr][INFO] - Evaluating initial parameters
[2024-09-12 11:05:17,908][flwr][INFO] - initial parameters (loss, other metrics): 32.087511189778645, {'accuracy': 0.43833333333333335}
[2024-09-12 11:05:17,911][flwr][INFO] - FL starting
[2024-09-12 11:05:17,912][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 11:05:32,622][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=11844, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 45, in fit
    train(self.model, self.trainloader, optimizer, epochs, self.device)
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\model.py", line 28, in train
    optimizer.zero_grad()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'functools.partial' object has no attribute 'zero_grad'
[2024-09-12 11:05:39,329][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16948, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 45, in fit
    train(self.model, self.trainloader, optimizer, epochs, self.device)
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\model.py", line 28, in train
    optimizer.zero_grad()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'functools.partial' object has no attribute 'zero_grad'
[2024-09-12 11:05:39,335][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-12 11:05:39,392][flwr][INFO] - fit progress: (1, 32.087511189778645, {'accuracy': 0.43833333333333335}, 21.47999350000009)
[2024-09-12 11:05:39,394][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
