[2024-09-12 10:55:27,605][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-09-12 10:55:42,756][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 8.0, 'object_store_memory': 810361651.0, 'node:__internal_head__': 1.0, 'node:127.0.0.1': 1.0, 'memory': 1620723303.0}
[2024-09-12 10:55:42,758][flwr][INFO] - Initializing global parameters
[2024-09-12 10:55:42,759][flwr][INFO] - Requesting initial parameters from one random client
[2024-09-12 10:55:48,957][flwr][INFO] - Received initial parameters from one random client
[2024-09-12 10:55:48,958][flwr][INFO] - Evaluating initial parameters
[2024-09-12 10:55:49,017][flwr][INFO] - initial parameters (loss, other metrics): 0.8913227319717407, {'accuracy': 0.45222222222222225}
[2024-09-12 10:55:49,021][flwr][INFO] - FL starting
[2024-09-12 10:55:49,022][flwr][DEBUG] - fit_round 1: strategy sampled 2 clients (out of 2)
[2024-09-12 10:55:49,079][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=16652, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 42, in fit
    optimizer = config.optimizer
                ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'optimizer'
[2024-09-12 10:55:55,471][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=8028, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 1896, in ray._raylet.execute_task
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\miniconda3\envs\flower\Lib\site-packages\flwr\client\app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Francesco\Desktop\PoliMi\Magistrale\Tesi\Progetto\Tesi-Francesco\client.py", line 42, in fit
    optimizer = config.optimizer
                ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'optimizer'
[2024-09-12 10:55:55,477][flwr][DEBUG] - fit_round 1 received 0 results and 2 failures
[2024-09-12 10:55:55,533][flwr][INFO] - fit progress: (1, 0.8913227319717407, {'accuracy': 0.45222222222222225}, 6.511719900000571)
[2024-09-12 10:55:55,535][flwr][DEBUG] - evaluate_round 1: strategy sampled 2 clients (out of 2)
